export const FETCH_GET_PROMOS = 'FETCH_PROMOS'
export const  GET_PROMOS_SUCCESS= 'GET_PROMOS_SUCCESS'
export const GET_PROMOS_FAILED = 'GET_PROMOS_FAILED'
export const FETCH_ADD_PROMO = 'FETCH_ADD_PROMO'
export const ADD_PROMO_SUCCESS = 'ADD_PROMO_SUCCESS'
export const ADD_PROMO_FAILED = 'ADD_PROMO_FAILED'
export const BLOCK_PROMO = 'BLOCK_PROMO'
export const BLOCK_PROMO_FAILED = 'BLOCK_PROMO_FAILED'

