export const GET_SHOPS_SUCCESS = 'GET_USERS_SAGA';
export const FETCH_GET_SHOPS = 'FETCH_GET_SHOPS';
export const GET_SHOPS_FAILED = 'GET_SHOPS_FAILED';
export const GET_AUTOCOMPLETE = 'GET_AUTOCOMPLETE'
export const GET_AUTOCOMPLETE_SUCCESS= 'GET_AUTOCOMPLETE_SUCCESS'
export const GET_PLACE_BY_ID = 'GET_PLACE_BY_ID'
export const GET_PLACE_BY_ID_SUCCESS = 'GET_PLACE_BY_ID_SUCCESS'
export const FETCH_ADD_SHOP = 'FETCH_ADD_SHOP'
export const ADD_SHOP_SUCCESS = 'ADD_SHOP_SUCCESS'
export const BLOCK_SHOP = 'BLOCK_SHOP'
export const BLOCK_SHOP_FAILED = 'BLOCK_SHOP_FAILED'
export const FETCH_ONLY_SHOP = 'FETCH_ONLY_SHOP'
export const GET_ONLY_SHOP_SUCCES = 'GET_ONLY_SHOP_SUCCES'
export const FETCH_EDIT_SHOP = 'FETCH_EDIT_SHOP'

export const EDIT_SHOP_SUCCESS = 'EDIT_SHOP_SUCCESS'
export const EDIT_SHOP_ERROR = 'EDIT_SHOP_ERROR'
