export const GET_SHOPS_SUCCESS = 'GET_USERS_SAGA';
export const FETCH_GET_SHOPS = 'FETCH_GET_SHOPS';
export const GET_SHOPS_FAILED = 'GET_SHOPS_FAILED';
export const GET_AUTOCOMPLETE = 'GET_AUTOCOMPLETE'
export const GET_AUTOCOMPLETE_SUCCESS= 'GET_AUTOCOMPLETE_SUCCESS'
export const GET_PLACE_BY_ID = 'GET_PLACE_BY_ID'
export const GET_PLACE_BY_ID_SUCCESS = 'GET_PLACE_BY_ID_SUCCESS'
