export const FETCH_GET_USER = 'FETCH_GET_USER'
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'
export const GET_USER_FAILED = 'GET_USER_FAILED'
export const FETCH_SET_USER = 'FETCH_SET_USER'
export const SET_USER_SUCCESS = 'SET_USER_SUCCESS'
export const SET_USER_FAILED = 'SET_USER_FAILED'
export const FETCH_BLOCK_USER = 'FETCH_BLOCK_USER'
export const BLOCK_USER_SUCCESS = 'BLOCK_USER_SUCCESS'
export const BLOCK_USER_FAILED = 'BLOCK_USER_FAILED'
export const FETCH_GET_ONLY_USER = 'FETCH_GET_ONLY_USER'
export const GET_ONLY_USER_SUCCESS = 'GET_ONLY_USER_SUCCESS'
export const GET_ONLY_USER_FAILED = 'GET_ONLY_USER_FAILED'


